apiVersion: v1
kind: Service
metadata:
  name: python-poetry
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: python-poetry
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-poetry
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-poetry
  template:
    metadata:
      labels:
        app: python-poetry
    spec:
      containers:
        - image: $TARGET_REPOSITORY:$TARGET_IMAGE_TAG
          name: python-poetry
          ports:
            - containerPort: 8080
