apiVersion: v1
kind: Service
metadata:
  name: jib-gradle
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jib-gradle
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jib-gradle
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jib-gradle
  template:
    metadata:
      labels:
        app: jib-gradle
    spec:
      containers:
        - image: $TARGET_REPOSITORY:$TARGET_IMAGE_TAG
          name: jib-gradle
          ports:
            - containerPort: 8080
